### PR TITLE
Fix PHP 8.2 dynamic property warning in ASN1.php

### PR DESCRIPTION
**Pull request by come-nc**

### CODE REVIEW

**Comment by terrafrost** [comment]
I cherry picked this into the 1.0 branch and then merged that into 2.0:

https://github.com/phpseclib/phpseclib/commit/74ee25bf8ae807eee4834bfca249624f05f3c919

Thanks!

**Comment by come-nc** [comment]
> I cherry picked this into the 1.0 branch and then merged that into 2.0:
> 
> [74ee25b](https://github.com/phpseclib/phpseclib/commit/74ee25bf8ae807eee4834bfca249624f05f3c919)
> 
> Thanks!

Thank you!
Do you have an idea when a new release will happen on branch 2.0?

**Comment by terrafrost** [comment]
I'll try to do a release this weekend.

Thanks!

**Comment by terrafrost** [comment]
I'm gonna push the release back to, latest, Wednesday.

I've been moving apartments this weekend and it took longer than anticipated! Still got unpacking to do and cleaning up to do at the old place but the hard part is over.

I apologize for the delay!

**Comment by come-nc** [comment]
> I'm gonna push the release back to, latest, Wednesday.
> 
> I've been moving apartments this weekend and it took longer than anticipated! Still got unpacking to do and cleaning up to do at the old place but the hard part is over.
> 
> I apologize for the delay!

No problem at all, take the time you need.
Thank you for working on this.

**Comment by terrafrost** [comment]
2.0.40 and 3.0.18 have been released.

Apologies for the delay.

Thanks!

**Pull request closed without merging**
