### PR TITLE
Proxy support

### PR DESCRIPTION
**Pull request by auro1**
If anyone wants to give a hand, just put a comment here and I'll grant you write access to the repo.
Stolen code from https://github.com/phpseclib/phpseclib/issues/474

DO __NOT__ MERGE THIS YET

### CODE REVIEW

**Comment by terrafrost** [comment]
It'd be easier to review the code if all the commits were squashed into one, altho idk if you're ready for it to be reviewed yet.

Anyway, I think, in theory, #746 kinda eliminates the need for this. Setup the SOCKS5 / HTTP(S) proxy outside of the SSH class and then pass the socket resource to the Net_SSH2 constructor.

**Comment by faridmovsumov** [comment]
@auro1 I have the same problem. Thanks for trying solve this problem. Does it work?

**Comment by BreakHear7** [comment]
Does it work with SSH?

**Comment by terrafrost** [comment]
#1460 demos SOCKS5 proxy support. https://github.com/phpseclib/phpseclib/issues/1339#issuecomment-462224179 demonstrates HTTP proxy support.

**Pull request closed without merging**
