### PR TITLE
[1.0] PHPDoc Fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Made possible by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1373, where case sensitive is set to false.

### CODE REVIEW

**Comment by bantu** [comment]
Hell yeah!

**Comment by GrahamCampbell** [comment]
Can we get this merged asap to stop other changes changes with wrong code going in.

**Comment by bantu** [comment]
@GrahamCampbell Yes

**Comment by bantu** [comment]
grep says this needs slightly more work, but these PRs are okay to merge IMO.

**Comment by bantu** [comment]
Specifially:
```
phpseclib/File/X509.php:     * @return String
phpseclib/Net/SSH2.php:     * @var mixed false or Array
phpseclib/Net/SSH1.php:     * @return string or Array
phpseclib/Net/SFTP.php:     * @return string or Array
phpseclib/Math/BigInteger.php:     * @param $input Array
phpseclib/Math/BigInteger.php:     * @param $x String
phpseclib/Math/BigInteger.php:     * @param $shift Integer
phpseclib/Math/BigInteger.php:     * @param $x String
phpseclib/Math/BigInteger.php:     * @param $shift Integer
```

**Comment by GrahamCampbell** [comment]
> @return String

That's odd.

> @param $shift Integer

Yeh - that needs manually fixing because the order is wrong. You've sad shift is the type an integer is the variable

**Comment by GrahamCampbell** [comment]
> @return string or Array

and that isn't valid syntax, so i couldn't fix it

**Comment by GrahamCampbell** [comment]
that is, automatially

**Pull request merged**
