### PR TITLE
Add 2.0.0 changelog

### LINKED ISSUE #842: 2.0 Changelog
Is there a changelog available for 2.0 since it has now been merged into master? Also, the website documentation seems to reference 1.0 still.

Thanks

### PR DESCRIPTION
**Pull request by mnapoli**
Fixes #842

### CODE REVIEW

**Comment by terrafrost** [comment]
I think what might be better is to put this stuff in the tag descriptions themselves:

https://github.com/phpseclib/phpseclib/releases

The justification being as follows:

https://github.com/phpseclib/phpseclib/pull/624
https://github.com/phpseclib/phpseclib/issues/756#issuecomment-130324051

Of course, no one has really weighed in on that proposal.

And it could just be that I suck at release management too meh. Like maybe what works for other projects doesn't work for me because it's an area I'm deficient in :(

That said...

```
- No autoloader is provided anymore (use Composer)
```

An autoloader was never provided. In the 1.0 branch `include`'s are done on required files at the time that they're required. In 2.0 an autoloader is mostly required. Technically, you could just load all the classes you knew were going to be using in advance, but that's a bit impractical.

What if, instead, that line read like this?:

```
- the use of an autoloader is now required
```

It may not be technically correct but for 99% of use cases it is.

**Comment by mnapoli** [comment]
Good call I've updated the file.

**Comment by terrafrost** [comment]
I squashed your two commits into one and then cherry-picked your commit into the 2.0 branch, which I then merged into the master branch:

https://github.com/phpseclib/phpseclib/blob/2.0/CHANGELOG.md
https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md

**Comment by mnapoli** [comment]
:+1:

**Pull request closed without merging**
