### PR TITLE
PSR-2 says use "elseif", not "else if"

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by terrafrost** [comment]
Looks good to me!

**Comment by GrahamCampbell** [comment]
:)

**Comment by bantu** [comment]
We should actually specify that we want PSR2. The code sniffer xml still checks for PEAR.

**Comment by bantu** [comment]
Hmm. Not sure we also want to switch the 1.0 branch to PSR2.

**Comment by GrahamCampbell** [comment]
@bantu Most of the code appears to already be psr2 in the 1.0 branch?

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by terrafrost** [comment]
I had kinda been hoping bantu would merge this since he was the one who voiced concerns about it and it is unclear to me if your observation constitutes a satisfactory response in his eyes.

I guess in lieu of a response from him I'll merge this this weekend.

**Comment by bantu** [comment]
I'll take care of it.

**Comment by bantu** [comment]
Discovered #671

**Comment by bantu** [comment]
Here is an extended version for changing to PSR2 https://github.com/phpseclib/phpseclib/compare/phpseclib:2.0...bantu:PSR2. Do we want that for 1.0 too?

**Comment by GrahamCampbell** [comment]
:+1: for 1.0 too

**Comment by terrafrost** [comment]
1.0 would be good!

**Comment by GrahamCampbell** [comment]
Ping. :)

**Comment by bantu** [comment]
@GrahamCampbell I'll convert everything to PSR2, so closing this.

**Pull request closed without merging**
