### PR TITLE
Remove old branch alias from 1.0 branch

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by bantu** [comment]
You will have to update the composer.lock file.

**Comment by GrahamCampbell** [comment]
Right, of course. I'll do this again...

**Comment by bantu** [comment]
Hmm. Where does Travis CI document changes? Is PHP 5.2 deprecated?

**Comment by GrahamCampbell** [comment]
> Hmm. Where does Travis CI document changes? Is PHP 5.2 deprecated?

PHP 5.2 was removed from travis for ever. Sorry. I only updated the docs for it a few days ago.

**Comment by GrahamCampbell** [comment]
PHP 5.3.3 will probably be going from travis when they move to ubuntu 14.04 too.

**Pull request closed without merging**
