### PR TITLE
Constant-time RFC-4648 encoding

### PR DESCRIPTION
**Pull request by paragonie-scott**
Supersedes #957 

(Will fix the autoloading in my next commit)

### CODE REVIEW

**Comment by paragonie-scott** [comment]
OK, I'm not sure why 5.5 is failing but 5.5.9 is passing, but I'm going to pause any tweaks for now.

**Comment by bantu** [comment]
@paragonie-scott The 5.5 environment runs the code sniffer. The problem is "There must be one blank line after the namespace "PSR2.Namespaces.NamespaceDeclaration.BlankLineAfter". See https://travis-ci.org/phpseclib/phpseclib/jobs/129270067#L577 and following.

**Comment by bantu** [comment]
@paragonie-scott Might want to fix the author/commiter on cda2cdc. There is a typo in the e-mail address.

**Comment by terrafrost** [comment]
Would you be up for doing this for the master branch instead?

In https://github.com/phpseclib/phpseclib/pull/957#issuecomment-203037624 I suggested that this would be fine in 2.0 if it was PSR-4 but I've since had a bit of a change of heart, in part due to #973. Among other things that made me realize was...  in a lot of the 2.0 examples I do this:

```php
include 'autoload.php';

$loader = new \Composer\Autoload\ClassLoader();
$loader->addPsr4('phpseclib\\', __DIR__ . '/path/to/phpseclib2.0');
$loader->register();
```

(where autoload.php is https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassLoader.php)

source: http://phpseclib.sourceforge.net/2.0.html

Problem is...  if people are doing that (as is done in the examples) then they'd have to add a new `$loader->addPsrR('...');` line to every file that's using phpseclib (assuming they're not using a common file). What would have been better is if I had just included autoload.php in the 2.0 branch. The vendor/composer directory could exist (maybe as a submodule) and autoload.php could have whatever lines it needed to have. And that one wouldn't be a submodule (or maybe it would be idk).

I mean, probably 95% of 2.0 users are using Composer but for the (guestimated) 5% that aren't this could cause problems. Meh :( This makes me glad that in the master / 3.0 branch I'm just requiring composer outright. You can certainly get phpseclib to work without composer but if you do so with master / 3.0 you're doing so at your own peril.

**Comment by paragonie-scott** [comment]
> There is a typo in the e-mail address.

Huh, I didn't even notice. Thanks.

> Would you be up for doing this for the master branch instead?

Sure, not a problem.

**Pull request closed without merging**
