### PR TITLE
Documentation Fixes for Scrutinizer

### PR DESCRIPTION
**Pull request by cnelissen**
This PR just adds a bunch of PHPDoc fixes (and other minor tweaks) to try to cut down on Scrutinizer errors in an attempt to make it a more useful debugging tool. Currently there is a lot of unnecessary noise in the reports, and this PR fixes a good deal of them.

### CODE REVIEW

**Comment by cnelissen** [comment]
Is there any interest in this PR? If not, we can go ahead and close it...

**Comment by terrafrost** [comment]
I'd say keep it open. It's very low priority but long-term it'd be good to get this stuff done.

**Comment by bantu** [comment]
We probably also want this in master.

**Comment by bantu** [comment]
This will be closed as the php5 will be going away. Feel free to send a new PR after #585 issues have been resolved.

**Pull request closed without merging**
