### PR TITLE
SSH_FXP_NAME packets appear to correspond to lstat - not stat / fix for 1.0 branch

### LINKED ISSUE #735: stat vs lstat
Hi,

With the latest 2.0 branch (489a723d33) I get the following bug.
The results should be equal, regardless of cache is disabled or not.

### My sample files:

    lrwxrwxrwx 1 root root    6 Jun 17 09:04 linkdir -> subdir
    lrwxrwxrwx 1 root root    8 Jun 17 09:04 link.txt -> text.txt
    drwxr-xr-x 2 root root 4096 Jun 17 09:04 subdir
    -rw-r--r-- 1 root root    5 Jun 17 09:03 text.txt

### My program:

    if ($is_cache === false) $sftp->disableStatCache();
    $files = $sftp->nlist();
    foreach($files as $name)
    {
        if ($name === "."  ||  $name === "..") continue;

        $stat = $sftp->stat($name);
        printf("%-11s: %6s %s %s\n", $name, $stat["size"], $stat["mtime"], $stat["type"]);

        $stat = $sftp->lstat($name);
        printf("%-11s: %6s %s %s\n", $name, $stat["size"], $stat["mtime"], $stat["type"]);
    }

### Wrong results with $is_cache==true  (Cache is enabled):

    linkdir    :      6 1434524668 3    <== wrong (stat)
    linkdir    :      6 1434524668 3
    link.txt   :      8 1434524693 3    <== wrong (stat)
    link.txt   :      8 1434524693 3
    text.txt   :      5 1434524636 1
    text.txt   :      5 1434524636 1
    subdir     :   4096 1434524643 2
    subdir     :   4096 1434524643 2

### Right results with $is_cache==false (Cache is disabled):

    linkdir    :   4096 1434524643 2
    linkdir    :      6 1434524668 3
    link.txt   :      5 1434524636 1
    link.txt   :      8 1434524693 3
    text.txt   :      5 1434524636 1
    text.txt   :      5 1434524636 1 
    subdir     :   4096 1434524643 2
    subdir     :   4096 1434524643 2

Best Regards
Michael

### PR DESCRIPTION
**Pull request by terrafrost**
Fixes #735. Replaces #736. I tried to squash the commits in #736 instead of doing a whole new PR but apparently I don't know what I'm doing :(

### CODE REVIEW

**Comment by bantu** [comment]
Arrrr. Looks like the rebase in #736 was not so good. Looks like repicking commits creates new commits that we do not want. So you have to refrain from using interactive rebase further than the point in history you want to change.

**Comment by terrafrost** [comment]
I'll keep that in mind in the future. Thanks! I'm assuming this PR is a-ok?

**Comment by bantu** [comment]
No, we don't want to duplicate those commits.

**Comment by bantu** [comment]
Replaced by #743

**Pull request closed without merging**
