### PR TITLE
Fix SSH2::login phpdoc

### LINKED ISSUE #1627: PHPDoc / Type hints are wrong
I have found multiple instances where the documented type hints in the library are wrong or inaccurate.

* `\phpseclib3\Net\SSH2::exec()` has `$callback` which has a type hint of `Callback` (notice the captial 'C'), which lets readers to believe there is a class `\phpseclib3\Net\Callback`.

* `\phpseclib3\Net\SSH2::login()`  has `@param string[] ...$args`, but going from the documentation you are expecting instances of `\phpseclib3\Crypt\RSA\PrivateKey` there, too.

Those are just two examples that I came across recently. Version 2 was even trickier to get around :D 

Do you have considered using tools like `phpstan` to avoid such issues?
PHPStan is pretty simple to include and helps avoid A LOT! of those issues.

I think you could rectify some of the documentation issues in a bug fix release, since your code might work, but the type hints are not correct. Technically it is not a breaking change that way.

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes #1627

cc @terrafrost

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Thanks a lot @terrafrost, do you mean doing a patch-release ? (Or is there any patch release planned soon ?)

**Comment by VincentLanglet** [comment]
Thanks a lot @terrafrost, do you mind doing a patch-release ? (Or is there any patch release planned soon ?)

**Comment by terrafrost** [comment]
@VincentLanglet - I just released new versions of 2.0 and 3.0.

Thanks!

**Comment by VincentLanglet** [comment]
Hi @MofX, either the phpdoc must be updated to `PrivateKey|AsymmetricKey` either the doc of this lib need to be updated.

I'm not sure if all the `AsymmetricKey` is really meant to be supported (or only some of them)

**Comment by MofX** [comment]
I don't know that either. I am not really familiar with the library only using it for a tiny project, that happens to use psalm for static type checking and I had to update phpseclib and that broke this check.
I'll leave fixing this up to the library experts :)

**Pull request merged**
