### PR TITLE
fix permission

### PR DESCRIPTION
**Pull request by remicollet**
Execution bit not needed

### CODE REVIEW

**Comment by terrafrost** [comment]
I cherry-picked this to 1.0 and merged that into 2.0 and master. Does it look better to you know?

Thanks!

**Comment by remicollet** [comment]
I don't understand, Net/SCP.php still have the exec bit set

**Comment by terrafrost** [comment]
When I tried to do `git cherry-pick remicollet/issue-perm` I got this message:

```
On branch 1.0
Your branch is ahead of 'origin/1.0' by 2 commits.
  (use "git push" to publish your local commits)
You are currently cherry-picking commit 9706f376.

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
```
I got that message on both Linux and Windows (Windows being what I chiefly develop on).

On Windows I tried `git commit --allow-empty` and then tried to do the cherry-pick again. It had been my hope that the permission change would stick.

After I made the commit and pushed it to https://github.com/terrafrost/phpseclib.git I did the following on my Linux machine:

```
git checkout -b test terrafrost/1.0
git log
cd phpseclib/
cd Net
ls -latr
```

And it showed the new permission. This convinced me that the permission change took and so I then pushed to https://github.com/phpseclib/phpseclib.git.

I'll now delete the entire phpseclib directory off of my Linux install and then re clone using https://github.com/phpseclib/phpseclib.git

**Comment by terrafrost** [comment]
It looks like the permissions took to the 1.0 branch but not to the 2.0 or master branches when I did `git merge 1.0`. Ugh.

**Comment by remicollet** [comment]
You don't have to apply this on 1.0, which is already ok.

Only in 2.0

This explain why you have a empty commit in 1.0, thus nothing in 2.0 (ans master)

**Pull request merged**
