### PR TITLE
[1.0] Static Code Analysis with Php Inspections (EA Extended) (splitting #752)

### PR DESCRIPTION
**Pull request by kalessil**
First part, compatible with PHP4 (no elvis operator, no dir constant)

### CODE REVIEW

**Comment by kalessil** [comment]
@bantu : merging my FB into local 2.0 went with conflicts, shall I revert conflicted files?

**Comment by bantu** [comment]
@kalessil Not necessary. We can probably easily fix them on merge.

**Comment by bantu** [comment]
This looks good to me, besides the `&` additions, which I can not comment on right now. @terrafrost Do you want to look into that?

**Comment by kalessil** [comment]
Adjusted.

**Comment by terrafrost** [comment]
Looks good to me now!

**Comment by bantu** [comment]
@kalessil This is seems to conflict heavily in 2.0. Can you provide a branch based on 2.0 with this PR merged into it?

**Comment by kalessil** [comment]
@bantu : yes, will do this tomorrow evening.

**Comment by kalessil** [comment]
Closing, will reopen as deal with workload

**Pull request closed without merging**
