### PR TITLE
SSH_FXP_NAME packets appear to correspond to lstat - not stat / fix for 1.0 branch

### LINKED ISSUE #735: stat vs lstat
Hi,

With the latest 2.0 branch (489a723d33) I get the following bug.
The results should be equal, regardless of cache is disabled or not.

### My sample files:

    lrwxrwxrwx 1 root root    6 Jun 17 09:04 linkdir -> subdir
    lrwxrwxrwx 1 root root    8 Jun 17 09:04 link.txt -> text.txt
    drwxr-xr-x 2 root root 4096 Jun 17 09:04 subdir
    -rw-r--r-- 1 root root    5 Jun 17 09:03 text.txt

### My program:

    if ($is_cache === false) $sftp->disableStatCache();
    $files = $sftp->nlist();
    foreach($files as $name)
    {
        if ($name === "."  ||  $name === "..") continue;

        $stat = $sftp->stat($name);
        printf("%-11s: %6s %s %s\n", $name, $stat["size"], $stat["mtime"], $stat["type"]);

        $stat = $sftp->lstat($name);
        printf("%-11s: %6s %s %s\n", $name, $stat["size"], $stat["mtime"], $stat["type"]);
    }

### Wrong results with $is_cache==true  (Cache is enabled):

    linkdir    :      6 1434524668 3    <== wrong (stat)
    linkdir    :      6 1434524668 3
    link.txt   :      8 1434524693 3    <== wrong (stat)
    link.txt   :      8 1434524693 3
    text.txt   :      5 1434524636 1
    text.txt   :      5 1434524636 1
    subdir     :   4096 1434524643 2
    subdir     :   4096 1434524643 2

### Right results with $is_cache==false (Cache is disabled):

    linkdir    :   4096 1434524643 2
    linkdir    :      6 1434524668 3
    link.txt   :      5 1434524636 1
    link.txt   :      8 1434524693 3
    text.txt   :      5 1434524636 1
    text.txt   :      5 1434524636 1 
    subdir     :   4096 1434524643 2
    subdir     :   4096 1434524643 2

Best Regards
Michael

### PR DESCRIPTION
**Pull request by terrafrost**
This merges cleanly into 2.0 and master.

Fixes #735

### CODE REVIEW

**Comment by bantu** [comment]
Let's please always use assertSame instead of assertEquals (=== vs ==).

**Comment by bantu** [comment]
Please squash  eab2740 into fe05dbd and 36b6324 into 66a7f4a.

**Comment by terrafrost** [comment]
How do I squash commits? I did the following:

```
git rebase -i HEAD~10

pick 52aeb2e Tests/SFTP: add unit test
pick c460e51 SFTP: update how recursive delete's update stat cache
pick 5a3315a Scrutinizer CI: Unconfigure external code coverage. This keeps timing out.
pick 109ae38 SFTP: don't update stat cache when it's been disabled
pick abeda52 Add support for RFC 4419: diffie-hellman-group-exchange-sha{1,256}
pick 41e72e7 SFTP: stat cache updates
squash fe05dbd Tests/SFTP: add unit test for last commit
squash 66a7f4a SFTP: add additional stat check
squash 36b6324 SFTP: syntax error
squash eab2740 rm accidentally added commit message file
squash 16b18c4 Tests/SSH2: change assertEquals to assertSame
```

I did `git log` and verified that the commit's had been squashed and then did `git push origin another-stat-cache-update-1.0`. That gave me the following:

```
To https://github.com/terrafrost/phpseclib.git
 ! [rejected]        another-stat-cache-update-1.0 -> another-stat-cache-update-1.0 (non-fast-forward)
error: failed to push some refs to 'https://github.com/terrafrost/phpseclib.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I then tried this:

```
git push origin --delete another-stat-cache-update-1.0
git push origin another-stat-cache-update-1.0
```

And now github.com is saying the branch has been deleted and isn't seeing the new (identically named) branch?

I'll just do another PR meh.

**Comment by bantu** [comment]
@terrafrost Your rebase looks good. When rewriting history like this and pushing to a PR branch, you will have to use the `-f` or `--force` option to replace the old commits with new commits. This option however MUST NOT be used for the blessed branches, i.e. 1.0, 2.0 and master. By using the `--delete` option, you deleted the repo branch and github subsequently closed the associated PR.

**Pull request closed without merging**
