### PR TITLE
Bug Report

### PR DESCRIPTION
**Pull request by hackimov**
Valid Base64 valid format did not pass validation in 10 cases out of 131,000. All signatures that did not pass regular expressions were more than 1 megabyte. One to two megabytes
I can provide this data, please contact me by telegram, please @alex_dirty. My name is Alexander Khakimov and I want to help you make your library better
I commented out a regex that did not correctly validate base64
I am passing base64 pkcs7 format to it to allow further decode of ASN1.

### CODE REVIEW

**Comment by terrafrost** [comment]
I'm going to need some unit tests for this that show this failing before and passing after. I don't suppose you could email the files to me? terrafrost@php.net .

I did install Telegram (which I've never used before) on my desktop. In order to add a new contact it's wanting me to add in their phone number. idk your phone number and I'm loathe to give out mine...

**Comment by hackimov** [comment]
Hello, I sent you an email with examples of files that did not pass validation.

Mail from supermehanikus@gmail.com . Zip archive with b64 format files.

Sorry for the delay, work does not always allow you to respond quickly.

**Comment by hackimov** [comment]
+998909024761 ( Telegram )

**Comment by terrafrost** [comment]
I think I like this better as a fix:

```php
        $temp = preg_match('#^-+BEGIN[^-]+-+[\r\n ]*$#ms', $str) ?
            preg_replace('#.*?^-+BEGIN[^-]+-+[\r\n ]*$#ms', '', $str, 1) :
            $str;
```
Anyway, now that I have your issues I should be able to create a much simpler unit test without your files.

I'll try to have that done within the next few days (got a busy week ahead of me).

Thanks!

**Comment by terrafrost** [comment]
Does https://github.com/phpseclib/phpseclib/commit/d077c7b29695ce26a45c4f4c0c56690726388d5c fix the issue?

**Comment by hackimov** [comment]
Perfect

**Pull request closed without merging**
