### PR TITLE
Use placeholder variables in list() calls

### PR DESCRIPTION
**Pull request by duncan3dc**
PHP7 does not support empty parameters in calls to list()

http://php.net/manual/en/migration70.incompatible.php

### CODE REVIEW

**Comment by bantu** [comment]
I am afraid I'll have to fix the unit tests some more.

**Comment by bantu** [comment]
Actual test failures introduced by your changes can be found here: https://travis-ci.org/phpseclib/phpseclib/jobs/75941904#L1461

**Comment by bantu** [comment]
On that page you linked to, I see a "Empty list() assignments have been removed" section. But most of the list() calls you are changing in phpseclib are in fact not empty, they are only missing some variables. Are you sure this is an issue with PHP 7.0? https://travis-ci.org/phpseclib/phpseclib/jobs/76047515 does not seem to complain about this either.

**Comment by duncan3dc** [comment]
Sorry for wasting your time, looks like I was misunderstanding an error and thought the cause was the missing `list()` parameter. You're right though, it seems to only affect missing parameters if there are __no__ parameters present

**Pull request closed without merging**
