### PR TITLE
Fix phpdoc errors reported by Doctum

### PR DESCRIPTION
**Pull request by williamdes**
Ref: #1513

### CODE REVIEW

**Comment by williamdes** [comment]
cc @terrafrost 
Did you see my pull-request ? :)

**Comment by terrafrost** [comment]
Sorry for the delay!

Anyway, this looks good to me!

Could you do this for the 2.0 branch as well? ie. merge your 1.0 branch into the 2.0 branch, resolve the merge conflicts, and then submit a PR for that one as well?

I guess the 3.0 branch is not currently as important. If it's not done for the 3.0 branch I'm probably not going to immediately do it. I'll still merge it in but I'll probably just merge it in in such a way that none of the changes stick (there _will_ be merge conflicts but in the merger all the original code will be preserved)

Thanks!!

**Comment by williamdes** [comment]
Sure, I I'll do it as soon as possible! :)

**Comment by williamdes** [comment]
Rebased.

For 1.x: #1514 (this one)
For 2.x: #1524 
For 3.x: #1525
For master: you can merge, no conflicts will appear

Command used on 3.x (maybe was different on 2.x) `php phpstan.phar analyse  --level=6 ./phpseclib --error-format=github | grep "PHPDoc tag @param"`

**Pull request merged**
