### PR TITLE
Timeout cannot be disabled(only refactoring)

### PR DESCRIPTION
**Pull request by torinaki**

### CODE REVIEW

**Comment by torinaki** [comment]
Here currently only small refactoring of timeout functionality to investigate #775

**Comment by terrafrost** [comment]
If you're wanting to test your changes against Travis CI you don't need to make a PR to do so - you can just create an account on travis-ci.org and then go to https://travis-ci.org/profile/torinaki , make sure that your fork of phpseclib is switched on. Then go to https://travis-ci.org/torinaki/phpseclib and check out the status.

**Comment by torinaki** [comment]
@terrafrost yeah I know possibility to run tests on my own branch. I have prepared this PR just for refactoring purpose. As I said didn't changed anything in this PR, because just done small refactoring. Currently SSH2 class methods has very high complexity and it's too hard to read/understand code.

**Comment by terrafrost** [comment]
My personal opinion: replacing one line of code with one function call is a little silly. Whereas before you could just trace through the code now, once you get to that function, you have to look that function up, and then go back to where you were at. And for what? Just to replace one line with another line?

I mean, if you're removing a lot of duplicated or re-usable code into a function that can be useful. But this doesn't really meet the "a lot of" test imho.

**Pull request closed without merging**
