### PR TITLE
(OpenSSL Big integer) Only require major version to match

### PR DESCRIPTION
**Pull request by haphan**
See issue [#597](https://github.com/phpseclib/phpseclib/issues/597)

### CODE REVIEW

**Comment by cnelissen** [comment]
This project uses PSR-2 as a coding standard, which is why your Travis checks are failing. Take a look at http://www.php-fig.org/psr/psr-2, specifically section 5. IF statements should like like:

```
if ($expr1) {
    // if body
} elseif ($expr2) {
    // elseif body
} else {
    // else body;
}
```

**Comment by haphan** [comment]
Thank you @cnelissen. I will fix and create pr again

**Comment by bantu** [comment]
Can you describe pre-patch and post-patch behaviour. It is not very clear to me, even after reading #597.

**Comment by bantu** [comment]
Can you please add spaces after "//" and squash all your commits?

**Comment by haphan** [comment]
@bantu done

**Comment by bantu** [comment]
@haphan Thanks.

**Pull request merged**
