### PR TITLE
Travis: compile GNU Parallel

### LINKED ISSUE #889: Travis CI always failing
See https://travis-ci.org/phpseclib/phpseclib/jobs/95074467

It's failing on `sudo apt-get install parallel`, giving an error of `E: Unable to locate package parallel`..

I think it may have something to do with https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

### PR DESCRIPTION
**Pull request by terrafrost**
Fixes #889

### CODE REVIEW

**Comment by terrafrost** [comment]
Doesn't seem like hhvm is working. I've created a ticket here:

https://github.com/travis-ci/travis-ci/issues/5243

In the mean time I guess I could go ahead and delete it from the .travis.yml file and re-add it depending on the outcome of that ticket idk..

**Comment by bantu** [comment]
There probably is a better mechanism for installing parallel than compiling it.

**Comment by bantu** [comment]
Tried https://github.com/composer/composer/blob/master/.travis.yml#L9-L12 ?

**Comment by terrafrost** [comment]
Doesn't seem to work :(

See https://github.com/terrafrost/phpseclib/commit/1765a0e5ba5bdf890eaef94e095116eebc0a1b48. Yielded a "sudo: must be setuid root" error:

https://travis-ci.org/terrafrost/phpseclib/jobs/95388741

The error that that change yielded is, I note, the same error I got when I commented out `sudo apt-get install parallel`.

I tried switching the order up as well:

https://travis-ci.org/terrafrost/phpseclib/jobs/95391493

Didn't help.

I note that in both of these jobs there was a "Installing APT Packages (BETA)" message that isn't present in the job for this PR.

**Comment by terrafrost** [comment]
I just went ahead and merged this.

If a better way to install GNU Parallel is found a new commit can be made.

If hhvm starts working on Travis a new commit can be made to re-enable it.

**Pull request merged**
