### PR TITLE
Convert Base::_createInlineCryptFunction to use PHP 5 anonymous functions instead of create_function

### PR DESCRIPTION
**Pull request by cnelissen**
This PR converts Base::_createInlineCryptFunction to use native PHP 5 anonymous functions instead of the PHP 4 create_function method. This is necessary for adding proper support for visibility statements throughout the codebase as the old lambda functions were not scope-aware and were causing visibility conflicts.

Additionally, the anonymous functions are showing a significant performance gain. Running the unit tests on the current version yields memory usage of 21.75Mb and running against this PR yields memory usage of 17.75Mb.

I am planning on further converting these functions to get rid of using eval statements, but I figured this should be good for a single PR.

Pre-requisite for #575

### CODE REVIEW

**Comment by bantu** [comment]
@terrafrost Do you want to look into performance implications of this PR?

**Comment by terrafrost** [comment]
I'll do that when I get home as time permits.

**Comment by terrafrost** [comment]
Before this commit internal mode takes 1.4 seconds. After this commit it takes 25 seconds. Need to figure out what's going on. My test code:

```php
<?php
include('autoloader.php'); // https://raw.githubusercontent.com/composer/composer/master/src/Composer/Autoload/ClassLoader.php

$loader = new \Composer\Autoload\ClassLoader();
$loader->addPsr4('phpseclib\\', __DIR__.'/phpseclib');
$loader->register();

use \phpseclib\Crypt\AES;

$plaintext = '';
for ($i = 0; $i < 1024*1024; $i++) {
    $plaintext.= chr(mt_rand(0, 255));
}

$start = microtime(true);

define('CRYPT_AES_MODE', AES::ENGINE_INTERNAL);
$aes = new AES();
$aes->setKey('abcdefghijklmnop');
$aes->encrypt($plaintext);
```

**Comment by cnelissen** [comment]
I am seeing similar results... I will mess around with the eval statements and see what I can do.

**Comment by bantu** [comment]
This will be closed as the php5 will be going away. Feel free to send a new PR.

**Pull request closed without merging**
