### PR TITLE
Get rid of func_get_args()

### PR DESCRIPTION
**Pull request by rrran**

### CODE REVIEW

**Comment by bantu** [comment]
This is probably useful to have. At least in master. Thanks.

**Comment by terrafrost** [comment]
Good call! I've done this in a few places already but hadn't done it everywhere. Thanks for taking the initiative!

**Comment by bantu** [comment]
Is there a code sniffer sniff for this? :-)

**Comment by rrran** [comment]
Yeah! grep -R  func_get_args ./
:) 
I'm using Linux and PHPStorm

**Pull request merged**
